---
name: Golang
"on":
  # required by gomod-go-version-updater to trigger this action once pr has
  # been reviewed
  pull_request_review:
    types: [submitted]
  push:
permissions:
  contents: read
  packages: read
jobs:
  mcvs-golang-action:
    strategy:
      matrix:
        args:
          - testing-type: component
          - testing-type: coverage
          - testing-type: integration
          - testing-type: lint
            build-tags: component
          - testing-type: lint
            build-tags: e2e
          - testing-type: lint
            build-tags: integration
          - testing-type: security-golang-modules
          - testing-type: security-grype
          - testing-type: security-trivy
          - testing-type: unit
    runs-on: ubuntu-24.04
    env:
      TASK_X_REMOTE_TASKFILES: 1
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: schubergphilis/mcvs-golang-action@v3.7.6
        with:
          code-coverage-expected: 0.0
          build-tags: ${{ matrix.args.build-tags }}
          golang-unit-tests-exclusions: |-
            \(cmd\/mcvs-scanner\|cmd\/mcvs-scanner-cli\|deprecated\|api\/swagger\|mocks\)
          testing-type: ${{ matrix.args.testing-type }}
