# yamllint disable rule:line-length
---
name: gomod-go-version-updater-action
"on":
  schedule:
    - cron: 42 5 * * 1-5
permissions:
  contents: write
  pull-requests: write
  repository-projects: write
jobs:
  gomod-go-version-updater-action:
    runs-on: ubuntu-22.04
    steps:
      - uses: schubergphilis/gomod-go-version-updater-action@17b37d0227071b60983a2729462c63021445fc0e # v0.3.6
